2017-09-20 08:59:07,783 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider 
2017-09-20 08:59:20,816 [nREPL-worker-0] ERROR db-devops.db.core - /Users/chenjinfen/Desktop/projects/CMB/IMAVP/2017/db-devops/05-dev/db-devops/user.edn (No such file or directory) 
2017-09-20 08:59:20,858 [nREPL-worker-0] ERROR db-devops.db.core - /Users/chenjinfen/Desktop/projects/CMB/IMAVP/2017/db-devops/05-dev/db-devops/verification.edn (No such file or directory) 
2017-09-20 08:59:20,867 [nREPL-worker-0] INFO  db-devops.env - 
-=[db_devops started successfully using the development profile]=- 
2017-09-20 08:59:21,314 [nREPL-worker-0] INFO  luminus.http-server - starting HTTP server on port 3000 
2017-09-20 08:59:21,439 [nREPL-worker-0] INFO  org.xnio - XNIO version 3.3.6.Final 
2017-09-20 08:59:21,703 [nREPL-worker-0] INFO  org.projectodd.wunderboss.web.Web - Registered web context / 
2017-09-20 08:59:51,126 [XNIO-1 task-32] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-20 09:03:56,012 [XNIO-1 task-23] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":{"USER":false,"NODENUM":1,"FS":false,"DB":false,"CHECK":"YES","DBM":false,"DB2VER":"V10.5.5","USERINFO":"asdf","CODEPAGE":"1386","INITDB2PATH":"asdf","DBNAME":"asdf","SYS":false,"DB2PATH":"asdfdsf","DBDATA":"1","HOSTNAME":"sdf","INST":false},"user_id":"admin","user_name":"admin","funcid":"CreateDB","label":"步骤1：创建数据库","shellNames":[{"shellID":"caller1","shellParams":[{"value":"inputParams.HOSTNAME"},{"value":"root"},{"value":"inputParams.INITDB2PATH"},{"name":"-DBDATASIZEGB","value":"inputParams.DBDATA"},{"name":"-USERINFO","value":"inputParams.USERINFO"},{"name":"-DB","value":"inputParams.DBNAME"},{"name":"-DB2PATH","value":"inputParams.DB2PATH"},{"name":"-DISKLIST","value":"inputParams.DISKLIST"},{"name":"-itil","value":"inputParams.itil"},{"name":"-CODEPAGE","value":"inputParams.CODEPAGE"},{"name":"-NODENUM","value":"inputParams.NODENUM"},{"name":"-DB2VER","value":"inputParams.DB2VER"},{"name":"-CHECK","value":"inputParams.CHECK"}]}]}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-20 09:03:56,223 [XNIO-1 task-23] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41694@1cd5f45c ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":{\"USER\":false,\"NODENUM\":1,\"FS\":false,\"DB\":false,\"CHECK\":\"YES\",\"DBM\":false,\"DB2VER\":\"V10.5.5\",\"USERINFO\":\"asdf\",\"CODEPAGE\":\"1386\",\"INITDB2PATH\":\"asdf\",\"DBNAME\":\"asdf\",\"SYS\":false,\"DB2PATH\":\"asdfdsf\",\"DBDATA\":\"1\",\"HOSTNAME\":\"sdf\",\"INST\":false},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateDB\",\"label\":\"步骤1：创建数据库\",\"shellNames\":[{\"shellID\":\"caller1\",\"shellParams\":[{\"value\":\"inputParams.HOSTNAME\"},{\"value\":\"root\"},{\"value\":\"inputParams.INITDB2PATH\"},{\"name\":\"-DBDATASIZEGB\",\"value\":\"inputParams.DBDATA\"},{\"name\":\"-USERINFO\",\"value\":\"inputParams.USERINFO\"},{\"name\":\"-DB\",\"value\":\"inputParams.DBNAME\"},{\"name\":\"-DB2PATH\",\"value\":\"inputParams.DB2PATH\"},{\"name\":\"-DISKLIST\",\"value\":\"inputParams.DISKLIST\"},{\"name\":\"-itil\",\"value\":\"inputParams.itil\"},{\"name\":\"-CODEPAGE\",\"value\":\"inputParams.CODEPAGE\"},{\"name\":\"-NODENUM\",\"value\":\"inputParams.NODENUM\"},{\"name\":\"-DB2VER\",\"value\":\"inputParams.DB2VER\"},{\"name\":\"-CHECK\",\"value\":\"inputParams.CHECK\"}]}]}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-20 14:27:01,365 [XNIO-1 task-5] INFO  db-devops.env - 
-=[db_devops has shut down successfully]=- 
2017-09-20 14:27:01,370 [XNIO-1 task-5] INFO  db-devops.env - 
-=[db_devops started successfully using the development profile]=- 
2017-09-20 14:27:06,674 [XNIO-1 task-25] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-20 14:27:13,232 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-20 14:27:13,235 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-20 14:27:13,293 [XNIO-1 task-32] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41694@1cd5f45c ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-20 14:27:15,368 [XNIO-1 task-26] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-20 14:27:15,370 [XNIO-1 task-26] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-20 14:27:15,378 [XNIO-1 task-26] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41694@1cd5f45c ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-20 14:27:17,467 [XNIO-1 task-28] DEBUG db-devops.upgrade-api-client - {:funcid :FreshNBU, :user_id admin} 
2017-09-20 14:27:17,468 [XNIO-1 task-28] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshNBU, :query-params {:user_id admin}} 
2017-09-20 14:27:17,482 [XNIO-1 task-28] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41694@1cd5f45c ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshNBU", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-20 14:27:19,880 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - {:funcid :FreshLocal, :user_id admin} 
2017-09-20 14:27:19,881 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshLocal, :query-params {:user_id admin}} 
2017-09-20 14:27:19,886 [XNIO-1 task-7] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41694@1cd5f45c ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshLocal", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
