2017-09-16 08:21:06,216 [XNIO-1 task-31] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 08:22:00,374 [XNIO-1 task-1] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":[{"SRCHOSTIP":"sadfsdf","TGPORT":"asdf","TGDBNAME":"df","SRCINSTANCENAME":"sdfds","TGHOSTNAME":"asdf","SRCHOSTNAME":"asdf","SRCPORT":"asdf","TGHOSTIP":"df","TGINSTANCENAME":"sdaf","SRCDBNAME":"sdf"}],"inputParam":{"POSTTASKNAME":"asdf"},"user_id":"admin","user_name":"admin","funcid":"CreateTSK","label":"步骤2：制定升级任务"}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-16 08:22:00,387 [XNIO-1 task-1] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":[{\"SRCHOSTIP\":\"sadfsdf\",\"TGPORT\":\"asdf\",\"TGDBNAME\":\"df\",\"SRCINSTANCENAME\":\"sdfds\",\"TGHOSTNAME\":\"asdf\",\"SRCHOSTNAME\":\"asdf\",\"SRCPORT\":\"asdf\",\"TGHOSTIP\":\"df\",\"TGINSTANCENAME\":\"sdaf\",\"SRCDBNAME\":\"sdf\"}],\"inputParam\":{\"POSTTASKNAME\":\"asdf\"},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateTSK\",\"label\":\"步骤2：制定升级任务\"}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:22:05,629 [XNIO-1 task-4] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:22:05,630 [XNIO-1 task-4] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:22:05,634 [XNIO-1 task-4] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:23:07,331 [XNIO-1 task-3] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 08:23:07,332 [XNIO-1 task-3] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 08:23:07,337 [XNIO-1 task-3] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:25:18,974 [XNIO-1 task-8] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:25:18,974 [XNIO-1 task-8] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:25:18,977 [XNIO-1 task-8] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:28:46,614 [XNIO-1 task-19] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 08:28:46,616 [XNIO-1 task-19] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 08:28:46,633 [XNIO-1 task-19] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:32:56,956 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:32:56,956 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:32:56,963 [XNIO-1 task-32] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:33:05,821 [XNIO-1 task-31] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:33:05,821 [XNIO-1 task-31] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:33:05,824 [XNIO-1 task-31] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:33:22,803 [XNIO-1 task-30] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 08:33:59,954 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:33:59,954 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:33:59,958 [XNIO-1 task-7] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:34:22,428 [XNIO-1 task-3] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 08:34:22,429 [XNIO-1 task-3] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 08:34:22,434 [XNIO-1 task-3] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:34:41,314 [XNIO-1 task-29] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 08:35:29,897 [XNIO-1 task-8] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":[{"SRCHOSTIP":"sdf","TGPORT":"asdf","TGDBNAME":"df","SRCINSTANCENAME":"sadf","TGHOSTNAME":"sdf","SRCHOSTNAME":"asdf","SRCPORT":"asdf","TGHOSTIP":"df","TGINSTANCENAME":"asdf","SRCDBNAME":"asdf"}],"inputParam":{"POSTTASKNAME":"asdf"},"user_id":"admin","user_name":"admin","funcid":"CreateTSK","label":"步骤2：制定升级任务"}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-16 08:35:29,904 [XNIO-1 task-8] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":[{\"SRCHOSTIP\":\"sdf\",\"TGPORT\":\"asdf\",\"TGDBNAME\":\"df\",\"SRCINSTANCENAME\":\"sadf\",\"TGHOSTNAME\":\"sdf\",\"SRCHOSTNAME\":\"asdf\",\"SRCPORT\":\"asdf\",\"TGHOSTIP\":\"df\",\"TGINSTANCENAME\":\"asdf\",\"SRCDBNAME\":\"asdf\"}],\"inputParam\":{\"POSTTASKNAME\":\"asdf\"},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateTSK\",\"label\":\"步骤2：制定升级任务\"}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:35:34,281 [XNIO-1 task-14] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 08:35:34,282 [XNIO-1 task-14] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 08:35:34,286 [XNIO-1 task-14] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:37:25,123 [XNIO-1 task-17] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 08:37:25,124 [XNIO-1 task-17] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 08:37:25,129 [XNIO-1 task-17] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:41:31,655 [XNIO-1 task-26] DEBUG db-devops.upgrade-api-client - {:funcid :FreshNBU, :user_id admin} 
2017-09-16 08:41:31,658 [XNIO-1 task-26] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshNBU, :query-params {:user_id admin}} 
2017-09-16 08:41:31,666 [XNIO-1 task-26] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshNBU", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:41:37,401 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - {:funcid :FreshLocal, :user_id admin} 
2017-09-16 08:41:37,401 [XNIO-1 task-32] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshLocal, :query-params {:user_id admin}} 
2017-09-16 08:41:37,405 [XNIO-1 task-32] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshLocal", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:41:47,768 [XNIO-1 task-28] DEBUG db-devops.upgrade-api-client - {:funcid :CompleteFresh, :user_id admin} 
2017-09-16 08:41:47,768 [XNIO-1 task-28] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CompleteFresh, :query-params {:user_id admin}} 
2017-09-16 08:41:47,771 [XNIO-1 task-28] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CompleteFresh", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 08:42:00,970 [XNIO-1 task-31] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 08:42:00,970 [XNIO-1 task-31] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 08:42:00,973 [XNIO-1 task-31] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 10:18:47,409 [XNIO-1 task-12] DEBUG db-devops.upgrade-api-client - {:taskname asfsdfsdfdsf} 
2017-09-16 10:18:47,411 [XNIO-1 task-12] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getAliasRecords/asfsdfsdfdsf, :query-params {}} 
2017-09-16 10:18:47,420 [XNIO-1 task-12] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getAliasRecords/asfsdfsdfdsf", :query-params {}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 10:18:54,917 [XNIO-1 task-15] DEBUG db-devops.upgrade-api-client - {:taskname chenjfsadf} 
2017-09-16 10:18:54,917 [XNIO-1 task-15] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getAliasRecords/chenjfsadf, :query-params {}} 
2017-09-16 10:18:54,921 [XNIO-1 task-15] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getAliasRecords/chenjfsadf", :query-params {}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:41:54,649 [XNIO-1 task-23] INFO  db-devops.env - 
-=[db_devops has shut down successfully]=- 
2017-09-16 14:41:54,654 [XNIO-1 task-23] INFO  db-devops.env - 
-=[db_devops started successfully using the development profile]=- 
2017-09-16 14:42:04,319 [XNIO-1 task-9] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 14:45:23,204 [XNIO-1 task-2] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":[{"SRCHOSTIP":"asfd","TGPORT":"sadf","TGDBNAME":"adsf","SRCINSTANCENAME":"asdf","TGHOSTNAME":"asdf","SRCHOSTNAME":"sdfsadf","SRCPORT":"asdf","TGHOSTIP":"sdf","TGINSTANCENAME":"asdf","SRCDBNAME":"asdf"}],"inputParam":{"POSTTASKNAME":"sdfasdf"},"user_id":"admin","user_name":"admin","funcid":"CreateTSK","label":"步骤2：制定升级任务"}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-16 14:45:23,211 [XNIO-1 task-2] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":[{\"SRCHOSTIP\":\"asfd\",\"TGPORT\":\"sadf\",\"TGDBNAME\":\"adsf\",\"SRCINSTANCENAME\":\"asdf\",\"TGHOSTNAME\":\"asdf\",\"SRCHOSTNAME\":\"sdfsadf\",\"SRCPORT\":\"asdf\",\"TGHOSTIP\":\"sdf\",\"TGINSTANCENAME\":\"asdf\",\"SRCDBNAME\":\"asdf\"}],\"inputParam\":{\"POSTTASKNAME\":\"sdfasdf\"},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateTSK\",\"label\":\"步骤2：制定升级任务\"}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:47:12,253 [XNIO-1 task-22] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 14:47:12,256 [XNIO-1 task-22] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 14:47:12,275 [XNIO-1 task-22] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:47:15,076 [XNIO-1 task-19] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 14:47:15,082 [XNIO-1 task-19] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 14:47:15,086 [XNIO-1 task-19] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:47:18,397 [XNIO-1 task-15] DEBUG db-devops.upgrade-api-client - {:funcid :FreshNBU, :user_id admin} 
2017-09-16 14:47:18,400 [XNIO-1 task-15] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshNBU, :query-params {:user_id admin}} 
2017-09-16 14:47:18,412 [XNIO-1 task-15] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshNBU", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:47:19,868 [XNIO-1 task-16] DEBUG db-devops.upgrade-api-client - {:funcid :FreshLocal, :user_id admin} 
2017-09-16 14:47:19,869 [XNIO-1 task-16] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshLocal, :query-params {:user_id admin}} 
2017-09-16 14:47:19,876 [XNIO-1 task-16] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshLocal", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:47:21,421 [XNIO-1 task-27] DEBUG db-devops.upgrade-api-client - {:funcid :CompleteFresh, :user_id admin} 
2017-09-16 14:47:21,422 [XNIO-1 task-27] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CompleteFresh, :query-params {:user_id admin}} 
2017-09-16 14:47:21,428 [XNIO-1 task-27] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CompleteFresh", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:49:36,391 [XNIO-1 task-13] INFO  db-devops.env - 
-=[db_devops has shut down successfully]=- 
2017-09-16 14:49:36,394 [XNIO-1 task-13] INFO  db-devops.env - 
-=[db_devops started successfully using the development profile]=- 
2017-09-16 14:49:36,480 [XNIO-1 task-13] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 14:49:36,480 [XNIO-1 task-13] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 14:49:36,486 [XNIO-1 task-13] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:49:38,987 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 14:49:38,987 [XNIO-1 task-7] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 14:49:38,991 [XNIO-1 task-7] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:49:39,583 [XNIO-1 task-9] DEBUG db-devops.upgrade-api-client - {:funcid :FreshNBU, :user_id admin} 
2017-09-16 14:49:39,584 [XNIO-1 task-9] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshNBU, :query-params {:user_id admin}} 
2017-09-16 14:49:39,588 [XNIO-1 task-9] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshNBU", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:49:40,123 [XNIO-1 task-10] DEBUG db-devops.upgrade-api-client - {:funcid :FreshLocal, :user_id admin} 
2017-09-16 14:49:40,124 [XNIO-1 task-10] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/FreshLocal, :query-params {:user_id admin}} 
2017-09-16 14:49:40,128 [XNIO-1 task-10] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/FreshLocal", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:49:40,696 [XNIO-1 task-8] DEBUG db-devops.upgrade-api-client - {:funcid :CompleteFresh, :user_id admin} 
2017-09-16 14:49:40,697 [XNIO-1 task-8] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CompleteFresh, :query-params {:user_id admin}} 
2017-09-16 14:49:40,701 [XNIO-1 task-8] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CompleteFresh", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:50:17,725 [XNIO-1 task-26] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 14:51:58,091 [XNIO-1 task-11] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":[{"SRCHOSTIP":"1.1.1.1","TGPORT":"43434","TGDBNAME":"sadf","SRCINSTANCENAME":"sadf","TGHOSTNAME":"asdfsdf","SRCHOSTNAME":"asdfsdf","SRCPORT":"33","TGHOSTIP":"2.2.2.2","TGINSTANCENAME":"asdfsdf","SRCDBNAME":"asdf"}],"inputParam":{"POSTTASKNAME":"asdfsdf"},"user_id":"admin","user_name":"admin","funcid":"CreateTSK","label":"步骤2：制定升级任务"}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-16 14:51:58,095 [XNIO-1 task-11] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":[{\"SRCHOSTIP\":\"1.1.1.1\",\"TGPORT\":\"43434\",\"TGDBNAME\":\"sadf\",\"SRCINSTANCENAME\":\"sadf\",\"TGHOSTNAME\":\"asdfsdf\",\"SRCHOSTNAME\":\"asdfsdf\",\"SRCPORT\":\"33\",\"TGHOSTIP\":\"2.2.2.2\",\"TGINSTANCENAME\":\"asdfsdf\",\"SRCDBNAME\":\"asdf\"}],\"inputParam\":{\"POSTTASKNAME\":\"asdfsdf\"},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateTSK\",\"label\":\"步骤2：制定升级任务\"}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 14:52:01,239 [XNIO-1 task-10] DEBUG db-devops.upgrade-api-client - {:funcid :CheckDB, :user_id admin} 
2017-09-16 14:52:01,240 [XNIO-1 task-10] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/CheckDB, :query-params {:user_id admin}} 
2017-09-16 14:52:01,243 [XNIO-1 task-10] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/CheckDB", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 15:35:33,509 [XNIO-1 task-2] DEBUG db-devops.upgrade-api-client - {:funcid :InitCDC, :user_id admin} 
2017-09-16 15:35:33,510 [XNIO-1 task-2] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :method :get, :url http://localhost:8080/rest/operationService/getTasks/InitCDC, :query-params {:user_id admin}} 
2017-09-16 15:35:33,515 [XNIO-1 task-2] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :method :get, :url "http://localhost:8080/rest/operationService/getTasks/InitCDC", :query-params {:user_id "admin"}}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
2017-09-16 17:53:59,764 [XNIO-1 task-12] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 19:08:37,527 [XNIO-1 task-20] INFO  db-devops.env - 
-=[db_devops has shut down successfully]=- 
2017-09-16 19:08:37,529 [XNIO-1 task-20] INFO  db-devops.env - 
-=[db_devops started successfully using the development profile]=- 
2017-09-16 19:08:42,234 [XNIO-1 task-18] INFO  db-devops.routes.services.auth - user: admin successfully logged in from 0:0:0:0:0:0:0:1 localhost 
2017-09-16 19:09:19,947 [XNIO-1 task-25] DEBUG db-devops.upgrade-api-client - request sent to upgrade API:  {:basic-auth [ooflow ooflow], :content-type :json, :body {"inputParams":{"ItilID":"asdf","USER":true,"NODENUM":34343,"FS":true,"DB":true,"CHECK":"NO","DISKLIST":"asdf","DBM":true,"DB2VER":"9.5","USERINFO":"asdf","CODEPAGE":"1386","DBNAME":"asdf","SYS":true,"DB2PATH":"asf","DBDATA":"5","HOSTNAME":"asdfasfd","INST":true},"user_id":"admin","user_name":"admin","funcid":"CreateDB","label":"步骤1：创建数据库","shellNames":[{"shellID":"caller1","shellParams":[{"value":"inputParams.HOSTNAME"},{"value":"root"},{"value":"inputParams.INITDB2PATH"},{"name":"-DBDATASIZEGB","value":"inputParams.DBDATA"},{"name":"-USERINFO","value":"inputParams.USERINFO"},{"name":"-DB","value":"inputParams.DBNAME"},{"name":"-DB2PATH","value":"inputParams.DB2PATH"},{"name":"-DISKLIST","value":"inputParams.DISKLIST"},{"name":"-itil","value":"inputParams.itil"},{"name":"-CODEPAGE","value":"inputParams.CODEPAGE"},{"name":"-NODENUM","value":"inputParams.NODENUM"},{"name":"-DB2VER","value":"inputParams.DB2VER"},{"name":"-CHECK","value":"inputParams.CHECK"}]}]}, :method :post, :url http://localhost:8080/rest/operationService/submitOperation} 
2017-09-16 19:09:19,955 [XNIO-1 task-25] ERROR db-devops.conditionhandling - Exception occured during calling function: clj_http.client$wrap_unknown_host$fn__41524@2ab45f5e ({:basic-auth ["ooflow" "ooflow"], :content-type :json, :body "{\"inputParams\":{\"ItilID\":\"asdf\",\"USER\":true,\"NODENUM\":34343,\"FS\":true,\"DB\":true,\"CHECK\":\"NO\",\"DISKLIST\":\"asdf\",\"DBM\":true,\"DB2VER\":\"9.5\",\"USERINFO\":\"asdf\",\"CODEPAGE\":\"1386\",\"DBNAME\":\"asdf\",\"SYS\":true,\"DB2PATH\":\"asf\",\"DBDATA\":\"5\",\"HOSTNAME\":\"asdfasfd\",\"INST\":true},\"user_id\":\"admin\",\"user_name\":\"admin\",\"funcid\":\"CreateDB\",\"label\":\"步骤1：创建数据库\",\"shellNames\":[{\"shellID\":\"caller1\",\"shellParams\":[{\"value\":\"inputParams.HOSTNAME\"},{\"value\":\"root\"},{\"value\":\"inputParams.INITDB2PATH\"},{\"name\":\"-DBDATASIZEGB\",\"value\":\"inputParams.DBDATA\"},{\"name\":\"-USERINFO\",\"value\":\"inputParams.USERINFO\"},{\"name\":\"-DB\",\"value\":\"inputParams.DBNAME\"},{\"name\":\"-DB2PATH\",\"value\":\"inputParams.DB2PATH\"},{\"name\":\"-DISKLIST\",\"value\":\"inputParams.DISKLIST\"},{\"name\":\"-itil\",\"value\":\"inputParams.itil\"},{\"name\":\"-CODEPAGE\",\"value\":\"inputParams.CODEPAGE\"},{\"name\":\"-NODENUM\",\"value\":\"inputParams.NODENUM\"},{\"name\":\"-DB2VER\",\"value\":\"inputParams.DB2VER\"},{\"name\":\"-CHECK\",\"value\":\"inputParams.CHECK\"}]}]}", :method :post, :url "http://localhost:8080/rest/operationService/submitOperation"}). Original exception message: java.net.ConnectException: Connection refused (Connection refused) 
